name: FreeBSD (OpenGL)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macos-12
    name: FreeBSD build

    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: git submodule update --init Tools/freebsd_x64
    - name: Compile in FreeBSD VM
      id: build
      uses: vmactions/freebsd-vm@v0.2.0
      with:
        usesh: true
        copyback: false
        mem: 2048
        prepare: pkg install -y bash alsa-lib libXinerama mesa-libs libXi xorg-vfbserver libXrandr libXi libXcursor evdev-proto libinotify ImageMagick7-nox11 libxkbcommon
        run: |
          echo " * Compile"
          ./make -g opengl --kinc . --from Tests/Empty --compile
          echo " * Clean"
          rm -r build
          echo " * Compile Test 1"
          ./make -g opengl --kinc . --from Tests/Shader --compile
          echo " * Copy Test 1"
          cp build/Release/ShaderTest Tests/Shader/Deployment/ShaderTest
          echo " * Run Test 1"
          cd Tests/Shader/Deployment
          bash -c '../../../Tools/freebsd-xvfb-run ./ShaderTest'
          cd ../../..
          echo " * Check Test 1"
          compare -metric mae Tests/Shader/reference.png Tests/Shader/Deployment/test.png difference.png
          echo " * Clean"
          rm -r build
          echo " * Compile Test 2"
          ./make --kinc . --from Tests/SIMD --compile
          echo " * Copy Test 2"
          cp build/Release/SIMD Tests/SIMD/Deployment/SIMD
          echo " * Run Test 2"
          cd Tests/SIMD/Deployment
          ./SIMD
          cd ../../..
