name: iOS (OpenGL)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Compile
      run: ./make ios -g opengl --kinc . --from Tests/Empty --noshaders --nosigning --compile
