name: Linux (OpenGL)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Apt Update
      run: sudo apt-get update
    - name: Apt Install
      run: sudo apt install libasound2-dev libxinerama-dev libxrandr-dev libgl1-mesa-dev libxi-dev libxcursor-dev libudev-dev --yes --quiet
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Compile
      run: Tools/kmake/kmake-linux64 -g opengl --kinc . --from Tests/Empty --compile
    - name: Get ImageMagick
      run: sudo apt install imagemagick
    - name: Compile and run Test 1
      run: Tools/kmake/kmake-linux64 -g opengl --kinc . --from Tests/Shader --run
    - name: Check Test 1
      run: compare-im6 -metric mae Tests/Shader/reference.png Tests/Shader/Deployment/test.png difference.png
