name: macOS (Metal)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: ./get_dlc
    - name: Compile
      run: ./make -g metal --kinc . --from Tests/Empty --compile
    - name: Compile and run Test 1
      run: ./make --kinc . --from Tests/Shader --run
    - name: Compile and Run Test 2 (SIMD)
      run: ./make --kinc . --from Tests/SIMD --run
