name: macOS (Metal)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Compile
      run: Tools/kmake/kmake-osx -g metal --kinc . --from Tests/Empty --compile
