name: macOS (Metal)

on:
  push:
    branches:
    - main
    - moarSIMD
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Compile
      run: Tools/kmake/kmake-osx -g metal --kinc . --from Tests/Empty --compile
    - name: Compile Test 2 (SIMD)
      run: Tools/kmake/kmake-osx --kinc . --from Tests/SIMD --compile --noshaders
    - name: Copy Test 2
      run: cp build/Release/SIMD Tests/SIMD/Deployment/SIMD
    - name: Run Test 2
      working-directory: ./Tests/SIMD/Deployment
      run: ./SIMD