name: Windows (Direct3D 12)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Compile
      run: .\Tools\kmake\kmake.exe -v vs2022 -g direct3d12 --kinc . --from Tests/Empty --noshaders --compile
