name: Windows (Direct3D 11)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Compile
      run: .\Tools\kmake\kmake.exe -v vs2019 -g direct3d11 --kinc . --from Tests/Empty --noshaders --compile
    - name: Download ImageMagick
      run: wget https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.1.0-portable-Q16-x64.zip
    - name: Unpack ImageMagick
      run: 7z x ImageMagick-7.1.0-portable-Q16-x64.zip
    - name: Compile and run Test 1
      run: .\Tools\kmake\kmake.exe -v vs2019 -g direct3d11 --kinc . --from Tests/Shader --noshaders --run
    - name: Check Test 1
      run: .\compare.exe -metric mae .\Tests\Shader\reference.png .\Tests\Shader\Deployment\test.tga difference.png
