name: Windows (Direct3D 9)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: .\get_dlc.bat
    - name: Compile
      run: .\make.bat -v vs2022 -g direct3d9 -a directsound --kinc . --from Tests/Empty --noshaders --compile
